# Site settings
title: Corrupted by the darkness now you fall into and endless sleep
description: "And other paths that result in failure and unnaceptance"
baseurl: ""
url: "https://nulligor.github.io"

# User settings
username: nulligor
user_title: Igor Soares
email: igor.larcs@gmail.com
instagram_username: overly.dramatic
github_username:  nulligor
codewars_username: ripfoghorn
devto_username: ripfoghorn
meetup_id: 221057668
resume_url: https://drive.google.com/file/d/1FO5dyQwqlBIIsSoPAKQqJ-DP127LWoVl/view
linkedin_public_url: nulligor
disqus_username: ripfoghorn
profile_picture: https://lh3.googleusercontent.com/d/1egZeXgHJsKn3GKwFmTbPBS0v7yhdNHQV

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: project-euler
    url: https://github.com/nulligor/project-euler
  - name: pmapv
    url: https://github.com/nulligor/pmapv
  - name: gull
    url: https://github.com/petlove/gull
  - name: drillr
    url: https://github.com/nulligor/drillr
  - name: stamps
    url: https://github.com/nulligor/stamps
exclude: ['package.json', 'src', 'node_modules']
